DROP TABLE Addresses;

CREATE TABLE Addresses
(
	ADDRESSID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	FIRSTNAME VARCHAR (15) NOT NULL,
	LASTNAME VARCHAR (30) NOT NULL,
	STREET VARCHAR (30) NOT NULL,
	CITY VARCHAR (15) NOT NULL,
        STATE VARCHAR (2) NOT NULL,
        ZIP VARCHAR (5) NOT NULL
);
INSERT INTO Addresses (FIRSTNAME,LASTNAME,STREET,CITY, STATE,ZIP)
	VALUES ('Sue','Black','1000 Michigan Ave','Chicago','IL','60605'),
	('James','Blue','1000 Harbor Ave','Seattle','WA','98116');
